version: "2.0"

services:
    db:
        image: umputun/mongo-auth
        restart: always
        environment:
            MONGO_PASSWD: app

    application:
        image: debian:jessie
        volumes:
            - ./project:/var/www
        tty: true

    python:
        build: docker/python
        restart: always
        container_name: angular-universal_python
        links:
            - db
        volumes_from:
            - application
        tty: true

    nodejs:
        build: docker/nodejs
        restart: always
        container_name: angular-universal_nodejs
        volumes_from:
            - application
        stdin_open: true
        tty: true

    nginx:
        build: docker/nginx
        restart: always
        links:
            - python
        volumes_from:
            - application
